### ISSUE TITLE
Xem đầu sách (Android)

### ISSUE THREAD

**Issue by monkeontheroof** [TrnLeDuy/LIBRARY_MANAGEMENT#1]
**Xử lý:**
- Adapter hiển thị dữ liệu danh sách các đầu sách cho Listview "Xem đầu sách" 
- Adapter liên kết dữ liệu từ ArrayList đầu sách 
- Hiển thị danh sách đầu sách từ Listview

**Lưu trữ:**
- Không

**Comment by doandang1501** [comment]
Giao diện: 
![Xemdausach](https://user-images.githubusercontent.com/124769928/230156673-a83f1b9d-4880-4d9b-aaa3-0f4a50f6f228.png)

**Comment by doandang1501** [comment]
Đang làm.

**Comment by doandang1501** [comment]
Đã xong.
