### ISSUE TITLE
Xem chi tiết thông tin sách (Android)

### ISSUE THREAD

**Issue by monkeontheroof** [TrnLeDuy/LIBRARY_MANAGEMENT#2]
**Giao diện:** 
Gồm các Textview thể hiện thông tin chi tiết của quyển sách, bao gồm:
- Tên sách
- Tác giả
- Năm xuất bản
- Tóm tắt nội dung
- Tình trạng (Còn/Hết)

Kèm một Imageview là trang bìa của sách

**Xử lý:**
- Chuyển về giao diện thông tin chi tiết sách sau khi chọn vào sách cần xem

**Lưu trữ:**
- Không

**Comment by doandang1501** [comment]
Đã nhận.

**Comment by doandang1501** [comment]
Đã xong.
