### ISSUE TITLE
Cập nhật tình trạng sử dụng thẻ thư viện 

### ISSUE THREAD

**Issue by DTPT128** [TrnLeDuy/LIBRARY_MANAGEMENT#26]
Giao diện:
-
- Có ListBox ngay cột tình trạng sử dụng thẻ để thay đổi trạng thái
- Có Button Xác nhận ở cuối form thông tin chi tiết

Xử lý:
-
- Chọn Button Chỉnh sửa ở Giao diện Xem thông tin chi tiết của thẻ thư viện
- Thay đổi tình trạng sử dụng thẻ thư viện của sinh viên (Hiệu lực/Vô hiệu quá) khi vi phạm yêu cầu sau:
  + Làm mất hoặc làm hử hỏng sách thì thẻ thư viện sẽ bị vô hiệu hóa tạm thời.
- Sau khi thay đổi thì chọn Button Xác nhận ở cuối form chi tiết thẻ thư viện

Lưu trữ:
-
- Cập nhật lại "tình trạng sử dụng" của bảng Thẻ thư viện trong cơ sở dữ liệu.

**Comment by doandang1501** [comment]
Done.
