### ISSUE TITLE
Thêm phiếu phạt 

### ISSUE THREAD

**Issue by DTPT128** [TrnLeDuy/LIBRARY_MANAGEMENT#27]
Giao diện:
-
- Hiển thị Form để nhập thông tin phiếu phạt, bao gồm các trường dữ liệu sau:
  + Mã thẻ thư viện
  + MSSV
  + Họ và tên sinh viên
  + Ngày lập thẻ phạt
  + Lý do
- Button Hoàn thành
- Button Hủy bỏ

Xử lý:
-
- Khi độc giả làm mất hoặc làm hỏng sách sẽ tiến hành nhập thông tin vào thẻ phạt.
- Điền tất cả thông tin cần thiết vào form 
- Sau khi nhập xong thì nhấn vào nút Hoàn thành để kết thúc quá trình tạo phiếu phạt
- Nhấn vào Hủy bỏ để ngừng thao tác điền form.

Lưu trữ:
-
- Thêm dữ liệu vào bảng Phiếu Phạt của Cơ sở dữ liệu

**Comment by doandang1501** [comment]
Done.
