### ISSUE TITLE
Thêm phiếu mượn sách

### ISSUE THREAD

**Issue by DTPT128** [TrnLeDuy/LIBRARY_MANAGEMENT#28]
Giao diện:
-
- Hiển thị form để nhập thông tin phiếu mượn sách và bao gồm các trường dữ liệu sau:
  + Mã thẻ thư viện
  + Họ và tên sinh viên
  + Ngày giờ mượn sách
  + Hạn mượn sách
  + Mã sách (Tự động được điền khi chọn tên sách tương ứng)
  + Tên sách (Dạng danh sách)
- Button Xác nhận mượn
- Button Hủy bỏ

Xử lý:
-
- Sau khi kiểm tra thẻ thư viện thì tiến hành chọn Mượn sách ở giao diện Dashboard
- Điền đầy đủ thông tin của form
- Nhấn Button Xác nhận mượn để hoàn tất quá trình tạo form
- Nhấn Button Hủy bỏ để ngừng quá trình tạo form

Lưu trữ:
-
- Thêm tất cả dữ liệu trên vào Bảng Mượn sách của Cơ sở dữ liệu

**Comment by doandang1501** [comment]
Done.
