### ISSUE TITLE
Xem danh sách tài khoản người dùng 

### ISSUE THREAD

**Issue by DTPT128** [TrnLeDuy/LIBRARY_MANAGEMENT#32]
Giao diện:
-
- Nút thêm người mới (Nhân viên)
- Danh sách tài khoản của các Nhân viên trong hệ thống
- Hiện lên màn hình là danh sách thông tin của người dùng đã đăng ký trong hệ thống (Nhân viên), gồm các trường dữ liệu sau:
  + Họ và tên người dùng
  + Tên tài khoản
  + Vai trò
- Giao diện Tài khoản:
  + Mã người dùng
  + Họ và tên người dùng
  + Ngày Sinh
  + Giới tính
  + Địa chỉ Email
  + Số điện thoại
  + Địa chỉ
Các nút Chỉnh sửa, Xóa (Danh sách nhân viên)
Các nút Chỉnh sửa, Chi tiết, Xóa (Danh sách Tài khoản)

Xử lý:
-
- Sau khi chọn Menu Người dùng sẽ chuyển sang màn hình danh sách, sau đó sẽ hiện lên danh sách tài khoản của người dùng hệ thống
- 

Lưu trữ:
-
- Không

**Comment by TrnLeDuy** [comment]
Đã hoàn tất
