### ISSUE TITLE
Xem danh sách các sinh viên đã đăng ký thẻ thư viện 

### ISSUE THREAD

**Issue by DTPT128** [TrnLeDuy/LIBRARY_MANAGEMENT#33]
Giao diện:
-
- Hiện lên màn hình là danh sách thông tin các sinh viên đã đăng ký thẻ thư viện, bao gồm các trường dữ liệu sau:
  + Mã thẻ
  + Mã sinh viên
  + Họ và tên sinh viên
  + Số điện thoại

Xử lý:
-
- Sau khi chọn trong Menu chuyển sang trang xem danh sách đã đăng ký thẻ thư viện, sau đó sẽ hiển thị lên màn hình danh sách

Lưu trữ:
-
- Không

**Comment by doandang1501** [comment]
Done.
