### ISSUE TITLE
Phân quyền 

### ISSUE THREAD

**Issue by DTPT128** [TrnLeDuy/LIBRARY_MANAGEMENT#36]
Giao diện:
-
Hiển thị danh sách Tài khoản gồm các cột sau:
             - Username
             - Họ và tên user
             - Role
             - Button tùy chọn ở cuối hàng | ... |
- Pop-up sau khi chọn vào nút Tùy chọn:
    - Xuất hiện dạng thẻ với các thông tin bao gồm: Username, Họ và tên, Role
    - Ở mục Role có nút để mở Danh sách Role
    - Button Xác nhận và Hủy bỏ ở bên phải dưới của trang pop-up

Xử lý: 
-
- Sau khi chọn button Tùy chọn của user muốn thay đổi sẽ pop-up giao diện Tùy chọn để bắt đầu thay đổi Role
- Nhấn vào nút mũi tên đi xuống ở mục Role để hiện ra danh sách Role
- Chọn role muốn thay đổi
- Nhấn chọn Xác nhận để hoàn tất quá trình thay đổi Role
- Nếu như trường hợp không muốn thay đổi nữa ta chọn nút Hủy bỏ để kết thúc tiến trình

Lưu trữ:
-
- Sau khi hoàn tất quá trình thay đổi Role => Cập nhật lại Role của User vừa được chỉnh sửa trên giao diện web vào trong Cơ sở dữ liệu

**Comment by TrnLeDuy** [comment]
Đã nhận và đang trong quá trình hoàn tất
