### ISSUE TITLE
Thêm Nhân Viên

### ISSUE THREAD

**Issue by DTPT128** [TrnLeDuy/LIBRARY_MANAGEMENT#37]
Giao diện:
-
- Hiển thị form Cập nhật tài khoản người dùng, yêu cầu các trường dữ liệu sau:
  + Họ và tên
  + Ngày sinh
  + Giới tính
  + Email
  + Số điện thoại
  + Địa chỉ
- Button Lưu
- Button Quay lại

Xử lý:
-
- Nhấn vào button Chỉnh sửa để bắt đầu điền thông tin tài khoản người dùng.
- Điền thông tin vào form Thêm tài khoản người dùng.
  + Họ và tên
  + Ngày sinh
  + Giới tính
  + Email
  + Số điện thoại
  + Địa chỉ
- Nhấn button Lưu để hoàn thành quá trình Cập nhật tài khoản người dùng.
- Nhấn button Quay lại để trở về trang Danh sách người dùng.

Lưu trữ:
-
- Sau khi Form thông tin Cập nhật tài khoản được điền đầy đủ và nhấn button Lưu thì cập nhật thông tin người dùng trong Cơ sở dữ liệu

**Comment by DTPT128** [comment]
Giao diện:
-
- Hiển thị form thêm tài khoản người dùng, yêu cầu các trường dữ liệu sau:
  + Fullname
  + Roles
  + Username
  + Password
  + Birth
  + Sex
  + Email 
  + Phone 
  + Address
- Button Thêm
- Button Hủy

Xử lý:
-
- Nhấn vào button Thêm tài khoản để bắt đầu điền thông tin tài khoản người dùng.
- Điền thông tin vào form Thêm tài khoản người dùng.
  + Fullname
  + Roles
  + Username
  + Password
  + Birth
  + Sex
  + Email 
  + Phone 
  + Address
- Nhấn button Xác nhận để hoàn thành quá trình Thêm tài khoản người dùng.
- Nhấn button Hủy để ngừng quá trình quá trình Thêm tài khoản người dùng.

Lưu trữ:
-
- Sau khi Form thông tin thêm tài khoản được điền đầy đủ và nhấn button Xác nhận thì cập nhật thông tin người dùng vào bảng User trong Cơ sở dữ liệu

**Comment by TrnLeDuy** [comment]
Đã nhận

**Comment by TrnLeDuy** [comment]
Đã xong
