### ISSUE TITLE
Cập nhật tài khoản người dùng 

### ISSUE THREAD

**Issue by DTPT128** [TrnLeDuy/LIBRARY_MANAGEMENT#38]
Giao diện:
- Hiển thị form chỉnh sửa thông tin tài khoản người dùng, yêu cầu các trường dữ liệu sau:
  + Fullname
  + Roles
  + Username
  + Password
  + Birth
  + Sex
  + Email 
  + Phone 
  + Address
- Button Xác nhận
- Button Hủy

Xử lý:
-
- Nhấn vào button Chỉnh sửa để bắt đầu quá trình chỉnh sửa thông tin người dùng.
- Điền vào textbox những thông tin cần chỉnh sửa.
- Nhấn button Xác nhận để hoàn thành quá trình Chỉnh sửa tài khoản người dùng.
- Nhấn button Hủy để ngừng quá trình quá trình Chỉnh sửa tài khoản người dùng.

Lưu trữ:
-
- Sau khi chỉnh sửa thành công sẽ cập nhật thông tin người dùng vào bảng User trong Cơ sở dữ liệu

**Comment by DTPT128** [comment]
Giao diện:
- Hiển thị form chỉnh sửa thông tin tài khoản người dùng, yêu cầu các trường dữ liệu sau:
  + Fullname
  + Roles
  + Username
  + Password
  + Birth
  + Sex
  + Email 
  + Phone 
  + Address
- Button Xác nhận
- Button Hủy
Xử lý:
- Nhấn vào button Chỉnh sửa để bắt đầu quá trình chỉnh sửa thông tin người dùng.
- Điền vào textbox những thông tin cần chỉnh sửa.
- Nhấn button Xác nhận để hoàn thành quá trình Chỉnh sửa tài khoản người dùng.
- Nhấn button Hủy để ngừng quá trình quá trình Chỉnh sửa tài khoản người dùng.
Lưu trữ:
- Sau khi chỉnh sửa thành công sẽ cập nhật thông tin người dùng vào bảng User trong Cơ sở dữ liệu

**Comment by TrnLeDuy** [comment]
Đã nhận

**Comment by TrnLeDuy** [comment]
Đã hoàn thành
