### ISSUE TITLE
Xóa tài khoản người dùng 

### ISSUE THREAD

**Issue by DTPT128** [TrnLeDuy/LIBRARY_MANAGEMENT#39]
Giao diện:
-
- Hiển thị danh sách người dùng và chọn thông tin người dùng cần xóa.

Xử lý:
-
- Chọn người dùng cần xóa, nhấn button Xóa để tiến hành xóa người dùng . 
- Màn hình hiện lên để xác nhận rằng chắc chắn muốn xóa. 
- Nhấn button Xác nhận để tiến hành xóa thông tin.
- Hoặc nhấn button Hủy để ngừng quy trình xóa và quay trở lại màn hình hiển thị thông tin người dùng. 

Lưu trữ:
-
- Sau khi xóa thành công sẽ cập nhật thông tin người dùng vào bảng User trong Cơ sở dữ liệu.

**Comment by DTPT128** [comment]
Giao diện:
-
- Hiển thị danh sách người dùng và chọn thông tin người dùng cần xóa.

Xử lý:
- Chọn người dùng cần xóa, nhấn button Xóa để tiến hành xóa người dùng . 
- Màn hình hiện lên để xác nhận rằng chắc chắn muốn xóa. 
- Nhấn button Xác nhận để tiến hành xóa thông tin.
- Hoặc nhấn button Hủy để ngừng quy trình xóa và quay trở lại màn hình hiển thị thông tin người dùng. 

Lưu trữ:
-
- Sau khi xóa thành công sẽ cập nhật thông tin người dùng vào bảng User trong Cơ sở dữ liệu.

**Comment by TrnLeDuy** [comment]
Đã nhận

**Comment by TrnLeDuy** [comment]
Đã hoàn thành
