### ISSUE TITLE
Đăng nhập

### ISSUE THREAD

**Issue by monkeontheroof** [TrnLeDuy/LIBRARY_MANAGEMENT#5]
**Giao diện:** 
- Màn hình đăng nhập: người dùng sẽ cần nhập tên đăng nhập và mật khẩu của mình để truy cập vào chức năng quản trị viên.
- Màn hình thông báo lỗi: nếu tên đăng nhập hoặc mật khẩu không chính xác, phần mềm sẽ hiển thị một thông báo lỗi cho người dùng.

**Xử lý:** 
- Khi người dùng nhập tên đăng nhập và mật khẩu và nhấn nút Đăng nhập, phần mềm sẽ kiểm tra tính hợp lệ của thông tin đăng nhập.
- Nếu thông tin đăng nhập chính xác, phần mềm sẽ cho phép người dùng truy cập vào chức năng quản trị viên. 
- Ngược lại, nếu thông tin đăng nhập không chính xác, phần mềm sẽ hiển thị một thông báo lỗi.

**Lưu trữ:** 
- Thông tin đăng nhập của quản trị viên sẽ được lưu trữ trong cơ sở dữ liệu của phần mềm.
- Cơ sở dữ liệu sẽ bao gồm một bảng để lưu trữ thông tin đăng nhập, bao gồm các trường như tên đăng nhập và mật khẩu của quản trị viên.
- Cơ sở dữ liệu sẽ được tạo ra và quản lý bởi phần mềm Android quản lý thư viện, và có thể được sao lưu và phục hồi nếu cần thiết.

**Comment by TrnLeDuy** [comment]
Đã nhận task

**Comment by TrnLeDuy** [comment]
Đã hoàn thành
