### ISSUE TITLE
Tạo giao diện Quản lý

### ISSUE THREAD

**Issue by monkeontheroof** [TrnLeDuy/LIBRARY_MANAGEMENT#6]
**Giao diện:**
- Màn hình chính: hiển thị danh sách sách trong thư viện, bao gồm tên sách, tác giả và ảnh bìa. Tại đây, người dùng có thể thực hiện tìm kiếm sách, xem chi tiết sách, thêm sách mới, sửa và xóa thông tin sách.
- Màn hình tìm kiếm: cho phép người dùng tìm kiếm sách theo tên, tác giả hoặc thể loại.
- Màn hình chi tiết sách: hiển thị thông tin chi tiết của một cuốn sách bao gồm tên sách, tác giả, thể loại, mô tả và ảnh bìa.

**Xử lý:** 
- Khi người dùng thực hiện tìm kiếm sách, phần mềm sẽ truy vấn cơ sở dữ liệu để lấy thông tin các cuốn sách liên quan đến từ khóa tìm kiếm.
- Khi người dùng thêm hoặc sửa thông tin sách, phần mềm sẽ kiểm tra tính hợp lệ của thông tin và lưu thông tin mới vào cơ sở dữ liệu.

**Lưu trữ:** 
- Các thông tin về sách, tác giả và thể loại sẽ được lưu trữ trong cơ sở dữ liệu của phần mềm.
- Ảnh bìa của sách sẽ được lưu trữ trong bộ nhớ của thiết bị Android.

**Comment by TrnLeDuy** [comment]
Đã nhận

**Comment by TrnLeDuy** [comment]
Đã hoàn thành tạo giao diện quản lý
